version: '3.7'
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "7772:1433"
    environment:
      SA_PASSWORD: "12qwasZX"
      ACCEPT_EULA: "Y"
  askon-test:
    image: lelique/askon-test
    container_name: askin-test
    environment:
    - ConnectionStrings__AskonConnection=Server=sql-server-db;Database=askon;User Id=sa;Password=12qwasZX;
    ports:
    - "5180:443"
    - "5179:80"
    depends_on:
    - sql-server-db
  askon-test-client:
    image: developer128/askon-test-client
    container_name: askon-test-client
    environment:
      API_HOST: "askon-test"
    ports:
    - "8080:8080"
    - "80:80"
    depends_on:
    - askon-test
